[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
jobs = 8
target = "firefly.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
